db_file: "data/scanb.sqlite"
app_title: "SCAN-B Mutation Explorer"
gene_protein_map_file: "data/gene_uniprot_mapping.tsv"

custom_genes:
  esr1_resistance:
    column: "mut.status.ESR1.resistance"
    label: "ESR1 Resistance Dahlgren et al (2019)"
