db_file: "data/scanb.sqlite"
app_title: "SCAN-B MutationExplorer"
gene_protein_map_file: "data/gene_uniprot_mapping.tsv"

table_header: "## Downloaded from: http://oncogenomics.bmc.lu.se/MutationExplorer\n## If you use this data in your research, please cite the following publication:\n## Brueffer et al (2019). bioRxiv. DOI: http://dx.doi.org/\n##\n"

custom_genes:
  esr1_resistance:
    column: "mut.status.ESR1.resistance"
    label: "ESR1 Resistance (Dahlgren et al, 2019)"
  pten_mutexp:
    column: "pten.mutexp"
    label: "PTEN Mutation and Gene Expression (Brueffer et al, 2019)"
    status:
      - "PTEN_LOW"
      - "PTEN_NORMAL"
  pten_exp:
    column: "pten.gex"
    label: "PTEN Gene Expression (Brueffer et al, 2019)"
    status:
      - "PTEN_LOW"
      - "PTEN_NORMAL"
